services:
  control-center:
    image: home-tunnel/control-center:dev
    build:
      context: ./control-center

  traffic-gateway:
    image: home-tunnel/traffic-gateway:dev
    build:
      context: ./traffic-gateway

  frps:
    image: home-tunnel/frps:0.70.1-dev
    build:
      context: ./deploy/frps
      args:
        FRP_VERSION: v0.70.1
        FRP_COMMIT: fa3bcca2b0c4753cd4f0e2ab189dd6a5a6a15708
