ARG NODE_IMAGE=node:22.17.1-bookworm-slim
FROM ${NODE_IMAGE}
ENV NODE_ENV=production
WORKDIR /app
COPY --chown=10001:10001 package.json ./package.json
COPY --chown=10001:10001 node_modules ./node_modules
COPY --chown=10001:10001 dist ./dist
COPY --chown=10001:10001 migrations ./migrations
COPY --chown=10001:10001 public ./public
USER 10001:10001
EXPOSE 8080
ENTRYPOINT ["node", "dist/server.js"]
