"""Generate the shared RD registry and deterministic binary vectors; --check is read-only."""
from pathlib import Path
import hashlib
import json
import struct
import sys
import uuid

ROOT = Path(__file__).resolve().parents[1]
source = ROOT / "contracts/remote-desktop.v1.json"
registry = json.loads(source.read_text(encoding="utf-8"))
messages = registry["messages"]
assert len({m["id"] for m in messages.values()}) == len(messages)
assert all(0 < m["id"] < 256 and m["channel"] in registry["channels"] for m in messages.values())
assert len(set(registry["permissions"])) == len(registry["permissions"])
encoded = json.dumps(registry, ensure_ascii=False, indent=2)
banner = "// Generated by scripts/generate-remote-protocol.py; do not edit.\n"
js = banner + "export const RD = Object.freeze(" + encoded + ");\n"
js += "export const TYPES = Object.freeze(" + json.dumps({name: m["id"] for name, m in messages.items()}) + ");\n"
cpp = banner + "#pragma once\n#include <cstdint>\nnamespace ht::rd::protocol {\n"
cpp += "inline constexpr std::uint16_t MAGIC = 0x5244;\ninline constexpr std::uint16_t HEADER_LENGTH = 24;\ninline constexpr std::uint8_t VERSION = 1;\n"
for name, value in registry["limits"].items():
    width = 64 if value > 0xffffffff else 32
    cpp += f"inline constexpr std::uint{width}_t {name.upper()} = {value}{'ull' if width == 64 else 'u'};\n"
for name, message in messages.items():
    cpp += f"inline constexpr std::uint8_t {name} = {message['id']};\n"
cpp += "}\n"
kotlin = banner + "package io.github.zhanry.hometunnel.remote.protocol\n\nobject RemoteProtocol {\n    const val MAGIC = 0x5244\n    const val HEADER_LENGTH = 24\n    const val VERSION = 1\n"
for name, value in registry["limits"].items():
    kotlin += f"    const val {name.upper()} = {value}{'L' if value > 2147483647 else ''}\n"
for name, message in messages.items():
    kotlin += f"    const val {name} = {message['id']}\n"
kotlin += "    val permissions = setOf(" + ", ".join(json.dumps(s) for s in registry["permissions"]) + ")\n}\n"
session = "00112233-4455-4677-8899-aabbccddeeff"
fields = [b"ht-rd-proof-v1", uuid.UUID(session).bytes]
transcript = b"".join(struct.pack(">I", len(field)) + field for field in fields) + struct.pack(">I", 3)
proof = {"session_id": session, "connection_epoch": 3}
for index, name in enumerate(("controller_nonce", "host_nonce", "offer_jws_sha256", "answer_jws_sha256", "ticket_sha256")):
    value = bytes(range(index * 32, (index + 1) * 32))
    proof[name] = value.hex()
    transcript += struct.pack(">I", len(value)) + value
proof.update(transcript_hex=transcript.hex(), sha256=hashlib.sha256(transcript).hexdigest())
crypto_vector = json.loads((ROOT / "contracts/remote-crypto-vector.json").read_text(encoding="utf-8"))
assert crypto_vector["transcript_sha256"] == proof["sha256"], "Crypto fixture must sign the current transcript"
proof.update({name: crypto_vector[name] for name in ("public_jwk", "public_key_xy_hex", "signature_raw64_hex")})
key_payload = struct.pack(">HHBBH", 7, 4, 1, 0, 0)
key_header = struct.pack(">HBBHHIIII", 0x5244, 1, messages["KEY"]["id"], 0, 24, 3, 7, 1, len(key_payload))
vectors = {"schema_version": 1, "proof": proof, "key_down_a": {"connection_epoch": 3, "input_epoch": 7, "sequence": 1, "usage_page": 7, "usage": 4, "wire_hex": (key_header + key_payload).hex()}}
outputs = {
    "contracts/generated/remote_protocol.js": js,
    "contracts/generated/remote_protocol.ts": js.replace(");\n", " as const);\n", 1),
    "contracts/generated/remote_protocol.hpp": cpp,
    "contracts/generated/remote_protocol.kt": kotlin,
    "contracts/remote-test-vectors.json": json.dumps(vectors, indent=2) + "\n",
    "control-center/public/modules/remote/protocol.generated.js": js,
}
for name, content in outputs.items():
    path = ROOT / name
    if "--check" in sys.argv:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            raise SystemExit(f"Regenerate {name}")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
print(f"RD protocol: {len(messages)} message types, {len(registry['permissions'])} permissions, 4 language registries and binary vectors verified")
