ARG NODE_IMAGE=node:22.17.1-bookworm-slim
FROM ${NODE_IMAGE}
ENV NODE_ENV=production
WORKDIR /app
COPY --chown=10001:10001 package.json ./package.json
COPY --chown=10001:10001 dist ./dist
USER 10001:10001
EXPOSE 8080
ENTRYPOINT ["node", "dist/server.js"]
